/*
####################
#    HEX Colors    # Change name and the values to the colors. #
####################
*/

#define C_WZ            0xFFFFFFFF
#define C_W2            0xFFFFFFFF
#define C_BLANCO        0xFFFFFFFF
#define C_ERROR         0xFFFFFFFF

/*
####################
#    CSS Colors    #
####################
*/
#define CWZ             "{FFFFFF}"
#define CWZ2            "{FFFFFF}"
#define CBLANCO         "{FFFFFF}"
#define CERROR          "{FFFFFF}"
#define CVERDE          "{FFFFFF}"
#define CMORADO     	"{FFFFFF}"
#define CNARANJA        "{FFFFFF}"

