main() {
    print("========================================");
    print("|*- index.pwn Cargado correctamente.   |");
    print("|                                      |");
    print("|*- Creditos:                          |");
    print("|                                      |");
    print("|*- KaizerHind - Developer.            |");
    print("|*- D13G0 - Helper in Code.            |");
    print("========================================");
}