main() {
    print("========================================");
    print("|*- index.pwn Cargado correctamente.   |");
    print("|                                      |");
    print("|*- Creditos:                          |");
    print("|                                      |");
    print("|*- KaizerHind - Developer.            |");
    print("|*- D13G0 - Doubts about MySql.        |");
    print("|*- root - Hash password solution.     |");
    print("|*- Galasso - Hash password solution.  |");
    print("========================================");
}