/*
##############################################################
#    HEX Colors  # Change name and the values to the colors. #
##############################################################
*/

#define C_NAMESV     0xA82C23FF
#define C_BLANCO     0xFFFFFFFF
#define C_NEGRO      0x0F0F0FFF
#define C_MONEY      0x0B6E27FF
#define C_ROJO       0xA70000FF
#define C_VERDE      0x15851DFF
#define C_NARANJA    0xC73B0CFF
#define C_CELESTE    0x02A8ADFF
#define C_AMARILLO   0xBFBC08FF
#define C_PURPURA    0x6A08BFFF
#define C_ROSA       0xAD02C7FF
#define C_ERROR      0x700101FF

/*
####################
#    CSS Colors    #
####################
*/

#define CNAMESV     "{a82c23}"
#define CBLANCO     "{ffffff}"
#define CNEGRO      "{0f0f0f}"
#define CMONEY      "{0b6e27}"
#define CROJO       "{a70000}"
#define CVERDE      "{15851d}"
#define CNARANJA    "{c73b0c}"
#define CCELESTE    "{02a8ad}"
#define CAMARILLO   "{bfbc08}"
#define CPURPURA    "{6a08bf}"
#define CROSA       "{ad02c7}"
#define CERROR      "{700101}"
